### PR TITLE
Further Dummy Item optimizing

### PR DESCRIPTION
**Pull request by Robijnvogel**
This should make that dummy item from the previous pull request actually work.

### CODE REVIEW

**Comment by Robijnvogel** [comment]
The dummy item doesn't correctly convert back into the original item yet...

**Comment by Robijnvogel** [comment]
Now it does.

Feel free to merge :)

I will probably work on config options for the Quantum Teleporters next.
I'm sorry if I'm kind of hi-jacking this project. :D

**Comment by kulttuuri** [comment]
Awesome! Merging :)

And it is really great to have someone working on this project :). I've found there's lots of potential in the project but there hasn't been people that have the ability to code Minecraft mods or a lot of people are just really busy on things in their life and do not have time for this. Myself included, upon MinecraftEdu, we've formed our second company and my life just revolves around that one :D

I also have account details for editing the original [Minecraft forum post](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292267-1-7-10-forge-ssp-smp-qcraft-quantum-physics-meets) too now, so I can start updating that as updates start popping up :)

Also if you want to continue working on the project further on, I could actually create a qCraft team in github for you to get stuff here faster and you could create new forum post in minecraft forum for this mod as it doesn't seem like the original post can be moved to new author.

**Comment by Robijnvogel** [comment]
That sounds awesome! Thank you very much.

Some notes about my situation and planning:
- I just started a new semester of my studies and it's going to consume most of my time.
- There's only one feature I'd still like to implement in the MC 1.7.10 version, before I would call it a qCraft 1.2.2 release: Configurability of the Quantum Teleporter's field size.
- Also, I could write a little description of the "Missing Item Container" for the qCraft Wiki, if you'd like.
- After this, it is going to take me a while to get qCraft to work on MC 1.8.9
- After that, I may be ready to create a new forum thread for it. Possibly under a new account: "qCraftTeam", so I can share the password with you/the McEdu team.

Expect this timeline to cover at least two months, in which I will ask you to publish two qCraft builds to CurseForge (and the qCraft website if needed) and eventually edit the qCraft MC Forum thread's OP to include a link to the new thread and have that original thread locked.

**Comment by kulttuuri** [comment]
Fantastic. Have you used Slack before? I'd like to setup a qCraft chat room for us to better organize things :)

**Comment by Robijnvogel** [comment]
Nope, never even heard of it.
I have Skype and Discord though.

**Comment by kulttuuri** [comment]
Alright, we can continue on chat PMs. Find me with my real name "Aleksi Postari" and add me :)

**Pull request merged**
