### PR TITLE
Fix "disentanglement" of falling QBlocks, Take 2

### LINKED ISSUE #9: Gravity-influenced entangled blocks can become 'out-of-sync' if falling
First mentioned here: TeacherGaming/qcraft-mod#5

If a gravity-influenced entangled block is falling, it will not resolve with it's entangled group to any other block type. This is noticeable when you resolve it to a non-gravity-influenced entangled block while falling and it remains a gravity-influenced entangled block. The 'out of sync' entangled block, once on the ground, will return to being in sync upon the next new observation.

Steps to reproduce:

1. Create a new creative mode world in single player.
2. Grab 4 blocks of a non-gravity-influenced block (stone), 4 blocks of a gravity-influenced block (sand), two Essence of Superposition, and one Essence of Entanglement.
3. Create two quantum blocks using the above ingredients, then use the Essence of Entanglement to entangle them.
4. Place a few of the entangled quantum blocks on the ground.
5. Using some block, build directly up next to your entangled quantum blocks until you are at a very high height.
6. Add an entangled quantum block at the top.
7. Make sure it is resolved to a non-gravity-influenced block and put on your Anti-Observation Goggles.
8. Remove all blocks that are below your high entangled quantum block.
9. Remove your Anti-Observation Goggles and resolve the entangled quantum blocks on the ground to a gravity-influenced block, then QUICKLY resolve them to a non-gravity-influenced block before the high entangled quantum block hits the ground.
10. Notice how the once high entangled quantum block remains a gravity-influenced block, even after hitting the ground.
11. When you resolve the blocks another time, everything returns to normal.

It is also possible to refrain from fixing this 'bug' and keeping it on as a feature. Would resolving a block to non-gravity-influenced while in-between two block positions cause a crash?

### PR DESCRIPTION
**Pull request by Robijnvogel**
Fixes what pull-request #5 fixed, without causing issue #6

Should fix #9 as well. I'm not entirely content with my fix though. It's kinda messy and I used some things I don't fully understand. Could someone have a look at that code please?

### CODE REVIEW

**Comment by kulttuuri** [comment]
This looks solid to me. @stanleyrya Can you have a look at this?

**Comment by Robijnvogel** [comment]
The fix for issue #9 is not that "neat", and I don't know if the method call on line 622 is right the way it is, but the code used there should only be called on entangled qBlocks that have just fallen and solidified, so I doubt anyone will ever run into a problem even if that method is used in a slightly wrong way.

What I mean to say is, I apologize in advance if this breaks anything, but I don't expect it will.

**Comment by stanleyrya** [comment]
I would love to test it out and look into it, but unfortunately I just left for a vacation. I'll let you guys know if I get lucky and find a computer to test it on :)

Otherwise I'll definitely take a look when I get back home (about two weeks)

**Comment by kulttuuri** [comment]
Seems to be working.

**Pull request merged**
