### PR TITLE
Restructured save system and use Forge logger

### PR DESCRIPTION
**Pull request by Robijnvogel**
QCraft now uses the Forge logging system instead of the Minecraft or
Java one. (in QCraft.java)
Restructured the whole file save system to use the system that is
offered by Forge. This solves several problems with the Entanglements
and Validations of portals sometimes being reset at random moments or on
server restart. (rest of changed files)

This should fix issue: #13 along with some issues that have not been reported yet.

At the moment of filing this, this version still needs to be play-tested.

### CODE REVIEW

**Comment by kulttuuri** [comment]
Can someone take a look at this? I'm going on a vacation and might not being able to verify.

**Comment by kulttuuri** [comment]
@stanleyrya ? :)

**Comment by Robijnvogel** [comment]
I playtested this build and it works just as well as I had hoped. :D

If you build this and upload it to qCraft.org and Curse I would change the version number to 1.2.1 though, to make it clearer that some things changed. If you want to, I can change the gradle.build file for this.

**Comment by kulttuuri** [comment]
Yup! Could you change the build.gradle version for this? :)

**Comment by Robijnvogel** [comment]
Kulttuuri, are you still alive? :P

**Comment by kulttuuri** [comment]
Done. Could you provide a build for me with this? :)

**Comment by Robijnvogel** [comment]
[Here](https://dl.dropboxusercontent.com/u/75152928/qCraft-1.2.1.jar) you go. :)

**Comment by kulttuuri** [comment]
Been taken long, but it's now live in qcraft.org and curse! :)

**Pull request merged**
